package caixin.android.com.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import caixin.android.com.entity.FriendEntity;
import caixin.android.com.entity.GroupEntity;
import caixin.android.com.entity.SendMessageResponse;

import caixin.android.com.dao.FriendEntityDao;
import caixin.android.com.dao.GroupEntityDao;
import caixin.android.com.dao.SendMessageResponseDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig friendEntityDaoConfig;
    private final DaoConfig groupEntityDaoConfig;
    private final DaoConfig sendMessageResponseDaoConfig;

    private final FriendEntityDao friendEntityDao;
    private final GroupEntityDao groupEntityDao;
    private final SendMessageResponseDao sendMessageResponseDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        friendEntityDaoConfig = daoConfigMap.get(FriendEntityDao.class).clone();
        friendEntityDaoConfig.initIdentityScope(type);

        groupEntityDaoConfig = daoConfigMap.get(GroupEntityDao.class).clone();
        groupEntityDaoConfig.initIdentityScope(type);

        sendMessageResponseDaoConfig = daoConfigMap.get(SendMessageResponseDao.class).clone();
        sendMessageResponseDaoConfig.initIdentityScope(type);

        friendEntityDao = new FriendEntityDao(friendEntityDaoConfig, this);
        groupEntityDao = new GroupEntityDao(groupEntityDaoConfig, this);
        sendMessageResponseDao = new SendMessageResponseDao(sendMessageResponseDaoConfig, this);

        registerDao(FriendEntity.class, friendEntityDao);
        registerDao(GroupEntity.class, groupEntityDao);
        registerDao(SendMessageResponse.class, sendMessageResponseDao);
    }
    
    public void clear() {
        friendEntityDaoConfig.clearIdentityScope();
        groupEntityDaoConfig.clearIdentityScope();
        sendMessageResponseDaoConfig.clearIdentityScope();
    }

    public FriendEntityDao getFriendEntityDao() {
        return friendEntityDao;
    }

    public GroupEntityDao getGroupEntityDao() {
        return groupEntityDao;
    }

    public SendMessageResponseDao getSendMessageResponseDao() {
        return sendMessageResponseDao;
    }

}
